### ISSUE TITLE
pre built binaries for arm64 aren't released in v0.3.14

### ISSUE THREAD

**Issue by suzuki-shunsuke** [mattn/goreman#139]
Hi, thank you for your great project.
I found pre built binaries for arm64 aren't released in v0.3.14.

https://github.com/mattn/goreman/releases/tag/v0.3.14

<img width="614" alt="image" src="https://user-images.githubusercontent.com/13323303/226074903-c2be4fcc-1f99-48d0-b1ef-ced5ff96ff45.png">

I guess this change was caused by https://github.com/mattn/goreman/pull/138 .

https://github.com/mattn/goreman/blob/eaf955cca418ea9ef2f21ce8ea7b433c6d2676d2/Makefile#L26-L28

I can't find the description about this change.

Why do you stop releasing pre built binaries for arm64?
Is there any plan to release pre built binaries for arm64 again?

## Background

I'm maintaining [a CLI Version Manager `aqua`](https://aquaproj.github.io/) and this tool supports goreman.

https://github.com/aquaproj/aqua-registry/blob/99100dc5bcec931e4489deaf8d867d4dd9195947/pkgs/mattn/goreman/registry.yaml

If goreman stops releasing pre built binaries for arm64, I have to fix the configuration for goreman.

**Comment by mattn** [comment]
Now released v0.3.15 for arm64.

https://github.com/mattn/goreman/releases/tag/v0.3.15

**Comment by suzuki-shunsuke** [comment]
Thank you!
