### ISSUE TITLE
export command

### ISSUE THREAD

**Issue by supermomonga** [mattn/goreman#15]
Is there any plan to implement [`export` command](http://ddollar.github.io/foreman/#EXPORTING)?

**Comment by mattn** [comment]
PRありがとうございます

**Comment by supermomonga** [comment]
実はPR送ったら採用される余地があるのか確認したかったので、やっていきます。

**Comment by mattn** [comment]
マージしました

**Comment by supermomonga** [comment]
やばい

**Comment by supermomonga** [comment]
WIPってるので近いうちにPR送ります

**Comment by mattn** [comment]
!

**Comment by jzorn** [comment]
So, what's the answer to that question?

**Comment by supermomonga** [comment]
I'm planning to send PR and currently working on.

**Comment by jzorn** [comment]
Ah sweet, thank you!

**Comment by do3cc** [comment]
Is there something half finished from which implementation could be continued?

**Comment by mattn** [comment]
Still not. But pull-request always welcome. :)

**Comment by mattn** [comment]
supported export https://github.com/mattn/goreman/commit/d34b02fada472a4291a27816e728181a89bf4ecf
