### ISSUE TITLE
Error in proc.go: ‘state’ declared and not used

### ISSUE THREAD

**Issue by Pensu** [mattn/goreman#16]
Hi,

I am trying to run a multi cluster with etcd and when I try to run goreman using "go get github.com/mattn/goreman", I get the following error:

$ go get github.com/mattn/goreman
# github.com/mattn/goreman
./proc.go:89:2: error: ‘state’ declared and not used
  state := true
  ^

Any idea what could be causing this?

**Comment by mattn** [comment]
Yes, you are right. But I can't reproduce it. I will fix in soon. But what version of go do you use?

**Comment by Pensu** [comment]
I am using go1.4.2.

$ go version
go version go1.4.2 gccgo (Ubuntu 5.1~rc1-0ubuntu1) 5.0.1 20150414 (prerelease) [gcc-5-branch revision 222102]

**Comment by mattn** [comment]
Ah, gccgo.

**Comment by Pensu** [comment]
Yeah, sorry, I guess I forgot to mention that!

**Comment by mattn** [comment]
Thanks for your answer.

**Comment by Pensu** [comment]
HI, I am running goreman as an example to run multi cluster etcd example. When I run "goreman start", I am getting this:
07:43:41 etcd3 | 2015/07/2 07:43:41 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)
07:43:41 etcd3 | 2015/07/2 07:43:41 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)
07:43:41 etcd2 | 2015/07/2 07:43:41 raft: 6e3bd23ae5f1eae0 is starting a new election at term 2631
07:43:41 etcd2 | 2015/07/2 07:43:41 raft: 6e3bd23ae5f1eae0 became candidate at term 2632
07:43:41 etcd2 | 2015/07/2 07:43:41 raft: 6e3bd23ae5f1eae0 received vote from 6e3bd23ae5f1eae0 at term 2632
07:43:41 etcd2 | 2015/07/2 07:43:41 raft: 6e3bd23ae5f1eae0 [logterm: 1, index: 3] sent vote request to 924e2e83e93f2560 at term 2632
07:43:41 etcd2 | 2015/07/2 07:43:41 raft: 6e3bd23ae5f1eae0 [logterm: 1, index: 3] sent vote request to a8266ecf031671f3 at term 2632
07:43:41 etcd2 | 2015/07/2 07:43:41 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)
07:43:41 etcd2 | 2015/07/2 07:43:41 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)
07:43:41 etcd2 | 2015/07/2 07:43:41 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)
07:43:41 etcd3 | 2015/07/2 07:43:41 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)
07:43:41 etcd3 | 2015/07/2 07:43:41 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)
07:43:42 etcd2 | 2015/07/2 07:43:42 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)
07:43:42 etcd2 | 2015/07/2 07:43:42 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)
07:43:42 etcd3 | 2015/07/2 07:43:42 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)
07:43:42 etcd3 | 2015/07/2 07:43:42 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)
07:43:42 etcd2 | 2015/07/2 07:43:42 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)
07:43:42 etcd2 | 2015/07/2 07:43:42 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)
07:43:42 etcd3 | 2015/07/2 07:43:42 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)
07:43:42 etcd3 | 2015/07/2 07:43:42 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)
07:43:42 etcd2 | 2015/07/2 07:43:42 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)
07:43:42 etcd2 | 2015/07/2 07:43:42 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)
07:43:42 etcd3 | 2015/07/2 07:43:42 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)
07:43:42 etcd3 | 2015/07/2 07:43:42 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)
07:43:42 etcd2 | 2015/07/2 07:43:42 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)
07:43:42 etcd2 | 2015/07/2 07:43:42 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)
07:43:42 etcd3 | 2015/07/2 07:43:42 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)
07:43:42 etcd3 | 2015/07/2 07:43:42 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)
07:43:42 etcd2 | 2015/07/2 07:43:42 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)
07:43:42 etcd2 | 2015/07/2 07:43:42 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)
07:43:42 etcd3 | 2015/07/2 07:43:42 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)
07:43:42 etcd3 | 2015/07/2 07:43:42 rafthttp: request sent was ignored (cluster ID mismatch: remote[a8266ecf031671f3]=7e27652122e8b2ae, local=e9c7614f68f35fb2)


Any idea what exactly is wrong here?

**Comment by mattn** [comment]
Could you please show me your Procfile?

**Comment by Pensu** [comment]
cat Procfile 
# Use goreman to run `go get github.com/mattn/goreman`
etcd1: /usr/bin/etcd -name infra1 -listen-client-urls http://localhost:4001 -advertise-client-urls http://localhost:4001 -listen-peer-urls http://localhost:7001 -initial-advertise-peer-urls http://localhost:7001 -initial-cluster-token etcd-cluster-1 -initial-cluster 'infra1=http://localhost:7001,infra2=http://localhost:7002,infra3=http://localhost:7003' -initial-cluster-state new
etcd2: /usr/bin/etcd -name infra2 -listen-client-urls http://localhost:4002 -advertise-client-urls http://localhost:4002 -listen-peer-urls http://localhost:7002 -initial-advertise-peer-urls http://localhost:7002 -initial-cluster-token etcd-cluster-1 -initial-cluster 'infra1=http://localhost:7001,infra2=http://localhost:7002,infra3=http://localhost:7003' -initial-cluster-state new
etcd3: /usr/bin/etcd -name infra3 -listen-client-urls http://localhost:4003 -advertise-client-urls http://localhost:4003 -listen-peer-urls http://localhost:7003 -initial-advertise-peer-urls http://localhost:7003 -initial-cluster-token etcd-cluster-1 -initial-cluster 'infra1=http://localhost:7001,infra2=http://localhost:7002,infra3=http://localhost:7003' -initial-cluster-state new
proxy: /usr/bin/etcd -name proxy1 -proxy=on -listen-client-urls http://localhost:8080 -initial-cluster 'infra1=http://localhost:7001,infra2=http://localhost:7002,infra3=http://localhost:7003'


I am using e one provided by etcd as it.

**Comment by mattn** [comment]
Hmm, I can't reproduce.
![](http://i.gyazo.com/e50fee6a0f3a7c55ad749e03f521fa9c.png)

**Comment by Pensu** [comment]
@mattn you are using gccgo or go compiler?

**Comment by mattn** [comment]
Since gccgo is not provided on windows, I use go compiler always.

**Comment by Pensu** [comment]
hmmm, could it be a gccgo issue then?

**Comment by mattn** [comment]
No, this is an issue of code of goreman.

See https://groups.google.com/forum/#!topic/golang-dev/QaAXYhC22G0

**Comment by mattn** [comment]
Well, the issue about etcd, may be not an issue of gccgo.

**Comment by Pensu** [comment]
Hmmm, I don't know any other player in the game! It's either etcd or gccgo!
