### ISSUE TITLE
There is also forego by @ddollar

### ISSUE THREAD

**Issue by koenpunt** [mattn/goreman#26]
Besides foreman, @ddollar also created forego:

https://github.com/ddollar/forego

**Comment by mattn** [comment]
https://github.com/mattn/goreman/issues/11

**Comment by koenpunt** [comment]
Oh well, missed that. Is there a difference between both implementations?

**Comment by mattn** [comment]
for example, RPC.

```
$ cat
web: ruby sinatra.rb
memcache: memcached -blah

$ goreman start
```
and below in another terminal

```
$ goreman run restart memcache
```
