### ISSUE TITLE
run stop can't pass SIGHUP to the grandchild process  

### ISSUE THREAD

**Issue by siddontang** [mattn/goreman#39]
I use goreman to run etcd local tester https://github.com/coreos/etcd/tree/master/tools/local-tester but find that `run stop` will hand up forever and the process can't be killed.  

Refer https://medium.com/@felixge/killing-a-child-process-and-all-of-its-children-in-go-54079af94773, I set `syscall.SysProcAttr{Setpgid: true}` to the SysProcAttr, and find it works well.

**Comment by mattn** [comment]
please send me PR

On 6/4/17, siddontang <notifications@github.com> wrote:
> I use goreman to run etcd local tester
> https://github.com/coreos/etcd/tree/master/tools/local-tester but find that
> `run stop` will hand up forever and the process can't be killed.
>
> Refer
> https://medium.com/@felixge/killing-a-child-process-and-all-of-its-children-in-go-54079af94773,
> I set `syscall.SysProcAttr{Setpgid: true}` to the SysProcAttr, and find it
> works well.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mattn/goreman/issues/39


-- 
- Yasuhiro Matsumoto
