### ISSUE TITLE
goreman with normal ip-address 

### ISSUE THREAD

**Issue by laic87** [mattn/goreman#42]
Hi 

Is it possible to use a normally ip address like 192.168.0.1 to start a cluster to connect through another PC with a jtcd client?

**Comment by mattn** [comment]
Currently, 127.0.0.1 is hardcoded.

https://github.com/mattn/goreman/blob/d0ee41b21be92ce6fd3e55ad11c5e5c9452fe822/rpc.go#L76

**Comment by mattn** [comment]
Now you can use $GOREMAN_RPC_SERVER for client. And $GOREMAN_RPC_ADDR and $GOREMAN_RPC_PORT for server.
