### ISSUE TITLE
basedir

### ISSUE THREAD

**Issue by Jacky-Chang** [mattn/goreman#43]
how can i use -basedir option?
when i use like this: goreman start -basedir "/usr/local/etcd/Procfile"
i got an error: open Procfile: no such file or directory

**Comment by monkeymorgan** [comment]
I see the same issue. I had to cd into the directory goreman is installed into to workaround this issue.

**Comment by ahrtr** [comment]
The correct command should be like this:
```
goreman start -basedir /usr/local/etcd -f Profile
```
Note that the file "Profile" should be in the basedir

**Comment by Jacky-Chang** [comment]
Thanks.
