### ISSUE TITLE
command to restart all services

### ISSUE THREAD

**Issue by nicksnyder** [mattn/goreman#45]
I would love to be able to restart all services that have been started with `goreman start`

e.g. `goreman restart`

**Comment by mattn** [comment]
closed by https://github.com/mattn/goreman/pull/46

**Comment by mattn** [comment]
Sorry, need explaining. I don't want to add restart command since restart command should be RPC. So I've added `run restart-all` command. Thank you.

**Comment by nicksnyder** [comment]
Thanks!
