### ISSUE TITLE
preserve order of spawning procs

### ISSUE THREAD

**Issue by vimalk78** [mattn/goreman#88]
Sometimes the configuration in `Procfile` is such that one process depends on execution of another. But currently there is no way to define order. The procs are read from file and pushed in a `map`. Iterating over the map does not give any guarantees on traversal, so procs are being spawned in any order.

If we use `"container/list"` instead of `map` , order of spawning procs can be same as order in the `procfile`.
https://github.com/mattn/goreman/blob/master/goreman.go#L66

I am not sure if this is a breaking change for users.

I can send a PR if you agree to change this.

**Comment by mattn** [comment]
Could you please try https://github.com/mattn/goreman/pull/89 ?
